[workspace]
members = ["core"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = [
    "nathaelb <pro.nathaelbonnal@gmail.com>",
    "baptisteparmantier <baptiste.parmantier@gmail.com>",
]
edition = "2024"
